# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SFIR Princeton
email: sfir@astro.princeton.edu 
description: > # this means to ignore newlines until "baseurl:"
  Star Formation/ISM seminars at Princeton
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sfirprinceton.github.io/" # the base hostname & protocol for your site
twitter_username: sfirprinceton
github_username:  sfirprinceton

# Build settings
markdown: kramdown
future: true
